name: Disparo Grupo Telegram

on:
  # Permite que o seu site (Frontend) chame este fluxo remotamente
  repository_dispatch:
    types: [iniciar_disparo]
  
  # Permite rodar manualmente pela aba "Actions" do GitHub para testes
  workflow_dispatch:
    inputs:
      video_url:
        description: 'Cole a URL do vídeo aqui'
        required: true
        type: string

jobs:
  publicar-no-grupo:
    runs-on: ubuntu-latest
    steps:
      - name: Baixar código do repositório
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Instalar bibliotecas necessárias
        run: |
          pip install requests beautifulsoup4

      - name: Executar Robô
        env:
          # Segredos configurados no GitHub (Settings > Secrets)
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          
          # Pega a URL vinda do site (payload) OU do input manual (workflow_dispatch)
          TARGET_URL: ${{ github.event.client_payload.video_url || inputs.video_url }}
        run: python automation.py
