name: Disparo Monetizado Telegram

on:
  repository_dispatch:
    types: [iniciar_disparo]
  workflow_dispatch:

jobs:
  publicar-no-grupo:
    runs-on: ubuntu-latest
    steps:
      - name: Baixar código
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Instalar FFmpeg e Fontes
        run: sudo apt-get update && sudo apt-get install -y ffmpeg fonts-liberation

      - name: Instalar Dependências
        run: pip install requests beautifulsoup4 cloudscraper yt-dlp

      - name: Executar Sniper Engine
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ github.event.client_payload.chat_id || secrets.TELEGRAM_CHAT_ID }}
          TARGET_URL: ${{ github.event.client_payload.video_url }}
          CUSTOM_MEDIA_URL: ${{ github.event.client_payload.custom_media_url }}
          SCRAPE_LIMIT: ${{ github.event.client_payload.scrape_limit }}
          VIDEO_DURATION: ${{ github.event.client_payload.video_duration }}
          WATERMARK_TEXT: ${{ github.event.client_payload.watermark_text }}
          WATERMARK_POS: ${{ github.event.client_payload.watermark_pos }}
          USE_SPOILER: ${{ github.event.client_payload.use_spoiler }}
          USE_TITLE: ${{ github.event.client_payload.use_title }}
          SEND_MODE: ${{ github.event.client_payload.send_mode }}
          CUSTOM_CAPTION: ${{ github.event.client_payload.caption_text }}
          DYNAMIC_BUTTONS: ${{ github.event.client_payload.dynamic_buttons }}
        run: python automation.py
